//scheme operations
export const INIT_SCHEME_REQUEST = 'INIT_SCHEME_REQUEST';
export const INIT_SCHEME_SUCCESS = 'INIT_SCHEME_SUCCESS';
export const INIT_SCHEME_FAIL = 'INIT_SCHEME_FAIL';

export const CHAR_VCO_REQUEST = 'CHAR_VCO_REQUEST';
export const CHAR_VCO_PENDING = 'CHAR_VCO_PENDING';
export const CHAR_VCO_SUCCESS = 'CHAR_VCO_SUCCESS';
export const CHAR_VCO_FAIL = 'CHAR_VCO_FAIL';

export const GET_MODEL_REQUEST = 'GET_MODEL_REQUEST';
export const GET_MODEL_PENDING = 'GET_MODEL_PENDING';
export const GET_MODEL_SUCCESS = 'GET_MODEL_SUCCESS';
export const GET_MODEL_FAIL = 'GET_MODEL_FAIL';

export const SAVE_SCHEME_DATA = 'SAVE_SCHEME_DATA';
export const SAVE_BLOCK_IN_SCHEME = 'SAVE_BLOCK_IN_SCHEME';
export const SAVE_PARAMETERS_DATA = 'SAVE_PARAMETERS_DATA';


